### ISSUE TITLE
[Bug] 启动Clash后TCP连接数暴增

### ISSUE THREAD

**Issue by NoahAmethyst** [Kuingsmile/clash-core#1]
### 先决条件

- [X] 我了解这里是官方开源版 Clash 核心仓库，**只提供开源版或者 Premium 内核的支持**
- [X] 我要提交 Clash 核心的问题，并非 Clash.Meta / OpenClash / ClashX / Clash For Windows 或其他任何衍生版本的问题
- [X] 我使用的是**本仓库**最新版本的 Clash 或 Clash Premium 内核
- [X] 我已经在 [Issue Tracker](……/) 中找过我要提出的 bug，**并且没有找到相关问题**
- [X] 我已经仔细阅读 [官方 Wiki](https://dreamacro.github.io/clash/) 并无法自行解决问题
- [ ] （非 Premium 内核必填）我已经使用 dev 分支版本测试过，问题依旧存在

### 版本

1.18

### 适用的作业系统

Linux

### 适用的硬件架构

amd64

### 配置文件

```YAML
正常的clash订阅配置文件
```

### 问题描述

当我在自己的服务器上启动clash并加载订阅的配置文件后，服务器tcp链接数量暴增
<img width="1107" alt="image" src="https://github.com/Kuingsmile/clash-core/assets/46391031/a765389f-cbff-4d4d-87dd-42b97c5c26d6">
当我尝试关闭clash服务，并重新启动，然后再关闭后，服务器的tcp连接数变化如下：
<img width="943" alt="image" src="https://github.com/Kuingsmile/clash-core/assets/46391031/1dd0bd76-0f57-4c5b-bdb1-63b80b2eb483">

**Comment by Kuingsmile** [comment]
这里只是clash-core源代码的备份，供下载使用，请勿在这里提问
