### ISSUE TITLE
[Bug] <需要 armv8 树莓派用的>

### ISSUE THREAD

**Issue by Mica-Ma** [Kuingsmile/clash-core#2]
### Prerequisites

- [X] I understand that this is the official open-source version of the Clash core, **only providing support for the open-source version or Premium version**
- [X] I am submitting an issue with the Clash core, not Clash.Meta / OpenClash / ClashX / Clash For Windows or any other derivative version
- [X] I am using the latest version of the Clash or Clash Premium core **in this repository**
- [X] I have searched at the [Issue Tracker](……/) **and have not found any related issues**
- [X] I have read the [official Wiki](https://dreamacro.github.io/clash/) **and was unable to solve the issue**
- [ ] (required for Premium core) I've tried the `dev` branch and the issue still exists

### Version

0.0

### Operating System

Linux

### Architecture

armv5, armv6, armv7

### Configuration File

```YAML
需要 armv8 树莓派用的
```

### Log

```Text
需要 armv8 树莓派用的
```

### Description

需要 armv8 树莓派用的

### Reproduction Steps

需要 armv8 树莓派用的

**Comment by Kuingsmile** [comment]
使用 [clash-linux-arm64-v1.18.0.gz](https://github.com/Kuingsmile/clash-core/releases/download/1.18/clash-linux-arm64-v1.18.0.gz)
